### ISSUE TITLE
Issues running with Expo 28 / Android

### ISSUE THREAD

**Issue by j1mie** [sonaye/react-native-behavior#10]
Hi there, I can't seem to get any of the examples running using Expo 28, on Android. 

If the indices prop is present it throws:
```bash
Invariant Violation: inputRange (4) and outputRange (2) must have the same length
```

If indices prop is removed, it throws:
```bash
Warning: Failed prop type: Invalid props.style key `states` supplied to `View`
```

This is using the [basic example found here](https://github.com/sonaye/haraka/blob/master/examples/basic.js).

This is a great idea for a project by the way, especially for React Native animation newbies such as myself, hoping to get to use it! Thanks.

**Comment by sonaye** [comment]
Hey @j1mie,

I haven't had the time to update to the examples yet, they are outdated. Can you please take a look at the list of the breaking changes [here](https://github.com/sonaye/haraka/blob/master/CHANGELOG.md#0021), it should help.

It's `state` now not `state(s)`, you also don't need to supply indices anymore on android, that bug has been fixed.

**Comment by sonaye** [comment]
I just updated a couple of examples to get you started, let me know if you face any issues.

**Comment by sonaye** [comment]
All the examples are updated now.
