### ISSUE TITLE
Any plans to migrate to react-native-reanimated?

### ISSUE THREAD

**Issue by bajedev** [sonaye/react-native-behavior#14]
The reanimated library is lower level and more performant, just wondering if we can expect migration anytime soon

**Comment by sonaye** [comment]
No plans at the moment, all the animations run on the native thread in Haraka so they are performant as well, reanimated would be useful for proprieties that are not supported by Animated. PRs welcome though!

**Comment by bajedev** [comment]
Yeah the library is near perfect and animations are smooth, my only issue is that if the JS thread is blocked then the animation is slow to start (that's why I was wondering about Reanimated), after that it works flawlessly. 

But I'm glad to hear that PRs are welcome, you'll probably be seeing one soon! Thanks!

This library is animation simplicity, keep up the good work!
